version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pritam01
      MYSQL_DATABASE: banking_db
      MYSQL_USER: bankuser
      MYSQL_PASSWORD: pritam01
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  api:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_NAME: banking_db
      DB_USER: bankuser
      DB_PASSWORD: pritam01
      DB_PORT: 3306
      JWT_SECRET: change_this_in_prod
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_data: